<?php
$this
        ->setTitle('Quản lý ứng dụng')
        ->setSideMenuActive('app');

use Libs\Setting;
?>

<div class="row">
    <div class="col-xs-12">
        <h1 class="page-header">Quản lý ứng dụng</h1>
    </div>
</div>

<form method="get" action="">
    <div class="row">
        <?php foreach (Setting::getAllApp() as $appId): ?>
            <?php $setting = new Setting($appId) ?>
            <div class="col-md-4">
                <div class="panel media pad-all">
                    <div class="media-left">
                        <span class="icon-wrap icon-wrap-sm icon-circle bg-gray">
                            <i class="fa fa-code fa-2x"></i>
                        </span>
                    </div>
                    <div class="media-body pad-lft">
                        <p class="text-2x mar-no text-thin text-mint"><?php echo $setting->xml->attributes()->name ?></p>
                        <h4></h4>
                        <p class="text-muted mar-no">
                            <?php if ($setting->xml->attributes()->active == 'true'): ?>
                                <button type="submit" class="btn btn-default btn-sm" name="deactivate" value="<?php echo $appId ?>">Vô hiệu hóa</button>
                            <?php else: ?>
                                <button type="submit" class="btn btn-success btn-sm" name="activate" value="<?php echo $appId ?>">Kích hoạt</button>
                            <?php endif; ?>
                        </p>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</form>

